export default {
  INIT_POKEMONS: "INIT_POKEMONS",
  GET_POKEMONS: "GET_POKEMONS",
  GET_POKEMON: "GET_POKEMON",
  GET_POKEMONS_FIGHT: "GET_POKEMONS_FIGHT",
  GET_POKEMONS_ERROR: "GET_POKEMONS_ERROR"
};
